from sys import platform

params = {
    "axes.labelsize": 10,
    "font.size": 10,
    "legend.fontsize": 10,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "savefig.dpi": 600,
    "axes.spines.right": False,
    "axes.spines.top": False,
    "text.usetex": False,
    "legend.labelspacing": 1,
    "legend.borderpad": 0.5,
    "legend.borderaxespad": 0.5,
    "axes.labelpad": 2,
    "axes.linewidth": 0.4,
    "patch.linewidth": 0.7,
    "lines.linewidth": 1,
    "lines.markersize": 8,
    "font.family": "Arial" if platform == "win32" else "Liberation Sans",
    "xtick.major.pad": 1.5,
    "xtick.major.size": 2.5,
    "xtick.major.width": 0.4,
    "xtick.minor.pad": 1.2,
    "xtick.minor.size": 1.5,
    "xtick.minor.width": 0.3,
    "xtick.direction": "in",
    "ytick.major.pad": 1.5,
    "ytick.major.size": 2.5,
    "ytick.major.width": 0.4,
    "ytick.minor.pad": 1.2,
    "ytick.minor.size": 1.5,
    "ytick.minor.width": 0.3,
    "ytick.direction": "in",
}
